// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoginUsuario
    {
        [JsonProperty("identificacion")]
        public string Identificacion { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }
    }

    public partial class LoginUsuario
    {
        public static LoginUsuario FromJson(string json) => JsonConvert.DeserializeObject<LoginUsuario>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this LoginUsuario self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
