// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType2
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Producto
    {
        [JsonProperty("CodigoProducto")]
        public long CodigoProducto { get; set; }

        [JsonProperty("NombreProducto")]
        public string NombreProducto { get; set; }

        [JsonProperty("Existencias")]
        public long Existencias { get; set; }

        [JsonProperty("BodegaUbicacion")]
        public string BodegaUbicacion { get; set; }
    }

    public partial class Producto
    {
        public static List<Producto> FromJson(string json) => JsonConvert.DeserializeObject<List<Producto>>(json, QuickType2.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Producto self) => JsonConvert.SerializeObject(self, QuickType2.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
